---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Cancel already running workflows if new ones are scheduled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    uses: ./.github/workflows/validation.yml

  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  mkdocs:
    uses: ./.github/workflows/docs.yml
    with:
      # On a push to main: "latest"
      # On a 1st party (non-fork) PR: "preview" (needs secrets access)
      # On a 3rd party (fork) PR: "build-only"
      # On a manual dispatch on main branch ref: "latest"
      # On a manual dispatch on another ref: "build-only"
      release_type: ${{
        github.event_name == 'push' && github.ref_name == 'main' && 'latest' ||
        github.event_name == 'pull_request' && (github.event.pull_request.head.repo.full_name == github.repository && 'preview' || 'build-only') ||
        github.event_name == 'workflow_dispatch' && (github.ref_name == 'main' && 'latest' || 'build-only') ||
        'build-only'
        }}
    secrets: inherit

  # Produce a pull request payload artifact with various data about the
  # pull-request event (such as the PR number, title, author, ...).
  # This data is then be picked up by status-embed.yml action.
  pr_artifact:
    name: Produce Pull Request payload artifact
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Pull Request Payload artifact
        id: prepare-artifact
        if: always() && github.event_name == 'pull_request'
        continue-on-error: true
        run: cat $GITHUB_EVENT_PATH | jq '.pull_request' > pull_request_payload.json

      - name: Upload a Build Artifact
        if: always() && steps.prepare-artifact.outcome == 'success'
        continue-on-error: true
        uses: actions/upload-artifact@v7
        with:
          name: pull-request-payload
          path: pull_request_payload.json
