name: Check labels

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  label-check:
    name: PR label check

    # Don't run in forks, they probably don't have the same labels set up
    if: github.repository_owner == 'py-mine'

    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Check there's no do-not-merge
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 0
          labels: |
            m: do-not-merge

      - name: Check there's no unreloved review
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 0
          labels: |
            s: needs review
            s: waiting for author

      - name: Check PR stalled
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 0
          labels: |
            s: stalled
